# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-10-19 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='phone',
            field=models.IntegerField(default='123456', verbose_name='电话'),
        ),
    ]
